# -*- coding: utf-8 -*-
"""Baby_Height_yolo11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5PvDzPdXUn3tMMNBucOMYRl3vqmk5yy
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a pretrained model
model = YOLO("yolo11s-pose.pt")

# Training model using COCO8-Pose datasets
results = model.train(data=f"coco8-pose.yaml", epochs=100, batch=64, imgsz=640)

metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.box.map  # map50-95
metrics.box.map50  # map50
metrics.box.map75  # map75
metrics.box.maps  # a list contains map50-95 of each category

results = model.predict("baby_1.jpeg", save=True)
for result in results:
  keypoints = result.keypoints.cpu().numpy()
  print(keypoints)



