# -*- coding: utf-8 -*-
"""coin_Yolov11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF1r3cjFz7nM0nolH4Jsjlml3o2LxA86

**🔧 1. Cek GPU dan Lokasi Direktori**
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""**2. Installasi YOLOv11 dan Library Pendukung**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics supervision roboflow
import ultralytics
ultralytics.checks()

!pip install roboflow

"""**3. Siapkan Folder Dataset dan Mengunduh Dataset dari Roboflow**"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

from google.colab import userdata
from roboflow import Roboflow

rf = Roboflow(api_key="YMS2kxkrOKbvAFkljA7I")
project = rf.workspace("coinsrec").project("coin-recognition-u1ebb")
version = project.version(18)
dataset = version.download("yolov11")

"""**4. Melatih Model YOLOv11**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolo11s.pt data={dataset.location}/data.yaml epochs=30 batch=32 imgsz=640 plots=True

"""**5. Menampilkan Hasil Pelatihan**"""

!ls /content/runs/detect/train/

from IPython.display import Image as IPyImage

IPyImage(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

from IPython.display import Image as IPyImage

IPyImage(filename=f'/content/runs/detect/train/results.png', width=600)

from IPython.display import Image as IPyImage

IPyImage(filename=f'/content/runs/detect/train/val_batch0_pred.jpg', width=600)

"""**6. Validasi Model Terlatih**"""

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

import os
HOME = os.getcwd()

"""**7. Inferensi (Prediksi) pada Gambar Baru**"""

!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source=koin.jpeg save=True